# Generated by Django 6.0.7 on 2026-07-10 08:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan_comptable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('montantHT', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tva', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montantTTC', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut', models.CharField(choices=[('impayee', 'Impayée'), ('payee', 'Payée'), ('partielle', 'Partielle')], default='impayee', max_length=20)),
                ('echeance', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='plan_comptable.tiers')),
            ],
        ),
    ]
