# Generated by Django 6.0.7 on 2026-07-10 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('fournisseur', 'Fournisseur'), ('client', 'Client'), ('personnel', 'Personnel'), ('etat', 'Etat'), ('associe', 'Associé')], max_length=20)),
                ('compte', models.CharField(blank=True, max_length=50, null=True)),
                ('soldeDebit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('soldeCredit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('achats', 'Achats'), ('ventes', 'Ventes'), ('caisse', 'Caisse'), ('banque', 'Banque'), ('od', 'Opérations Diverses')], max_length=20)),
                ('dernierNumero', models.IntegerField(default=0)),
                ('succursale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journaux', to='parametres.succursale')),
            ],
        ),
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('numero', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255)),
                ('classe', models.CharField(max_length=1)),
                ('type', models.CharField(choices=[('general', 'Général'), ('auxiliaire', 'Auxiliaire')], default='general', max_length=20)),
                ('lettable', models.BooleanField(default=False)),
                ('soldeDebit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('soldeCredit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_comptes', to='plan_comptable.comptecomptable')),
                ('tiers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes', to='plan_comptable.tiers')),
            ],
        ),
    ]
