# Generated by Django 6.0.7 on 2026-07-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_comptable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptecomptable',
            name='analytique_obligatoire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comptecomptable',
            name='code_poste_etats_financiers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comptecomptable',
            name='lettrable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comptecomptable',
            name='mouvementable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comptecomptable',
            name='sens_normal',
            field=models.CharField(blank=True, choices=[('debit', 'Débiteur'), ('credit', 'Créditeur'), ('aucun', 'Aucun')], default='aucun', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='comptecomptable',
            name='soumis_tva',
            field=models.BooleanField(default=False),
        ),
    ]
