# Generated by Django 6.0.7 on 2026-07-10 08:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('format', models.CharField(blank=True, max_length=50, null=True)),
                ('evolution', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
