# Generated by Django 6.0.7 on 2026-07-10 08:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LigneCompta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('libelle', models.CharField(max_length=255)),
                ('compte', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sens', models.CharField(choices=[('debit', 'Débit'), ('credit', 'Crédit')], max_length=10)),
                ('pointe', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LigneReleve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('libelle', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sens', models.CharField(choices=[('debit', 'Débit'), ('credit', 'Crédit')], max_length=10)),
                ('pointe', models.BooleanField(default=False)),
            ],
        ),
    ]
