# Generated by Django 6.0.7 on 2026-07-10 08:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan_comptable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecriture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('libelle', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('brouillard', 'Brouillard'), ('valide', 'Validé')], default='brouillard', max_length=20)),
                ('piece', models.CharField(blank=True, max_length=255, null=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures', to='plan_comptable.journal')),
                ('saisiePar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_saisies', to=settings.AUTH_USER_MODEL)),
                ('validePar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_validees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LigneEcriture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('libelleCompte', models.CharField(blank=True, max_length=255, null=True)),
                ('libelle', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('auxiliaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_auxiliaires', to='plan_comptable.comptecomptable')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='plan_comptable.comptecomptable')),
                ('ecriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='saisie.ecriture')),
            ],
        ),
    ]
