# Generated by Django 6.0.7 on 2026-07-10 08:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raisonSociale', models.CharField(max_length=255)),
                ('sigle', models.CharField(blank=True, max_length=50, null=True)),
                ('statutJuridique', models.CharField(blank=True, max_length=50, null=True)),
                ('rccm', models.CharField(blank=True, max_length=100, null=True)),
                ('idNat', models.CharField(blank=True, max_length=100, null=True)),
                ('nImpot', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('pays', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('devise', models.CharField(default='USD', max_length=10)),
                ('exerciceEnCours', models.CharField(max_length=4)),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Succursale',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('short', models.CharField(max_length=10)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cle', models.CharField(max_length=100, unique=True)),
                ('valeur', models.CharField(max_length=255)),
                ('categorie', models.CharField(max_length=100)),
                ('typeValeur', models.CharField(choices=[('string', 'String'), ('boolean', 'Boolean'), ('number', 'Number'), ('json', 'JSON')], default='string', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
