import type {
  Dossier,
  CompteComptable,
  Ecriture,
  Journal,
  Camion,
  Tiers,
  Facture,
  Immobilisation,
  AuditEntry,
  KPI,
  LigneReleve,
  LigneCompta,
  SiteInfo,
  Parametre,
} from './types';

export const SITES: SiteInfo[] = [
  { id: 'zambie', label: 'Zambie (Achats)', short: 'ZMB', color: 'hsl(142 71% 45%)' },
  { id: 'lubumbashi', label: 'Lubumbashi (Siege)', short: 'LUB', color: 'hsl(221 83% 53%)' },
  { id: 'sabri', label: 'Mine de Sabri', short: 'SAB', color: 'hsl(38 92% 50%)' },
  { id: 'frontiere', label: 'Frontieres (Douane)', short: 'FRO', color: 'hsl(280 65% 60%)' },
];

export const DOSSIERS: Dossier[] = [
  {
    id: 'd1',
    raisonSociale: 'TransAfrique Cement Trading SARL',
    sigle: 'TACT',
    statutJuridique: 'SARL',
    rccm: 'RCC/CD/HKT/2023/B-0142',
    idNat: '01-N8-K7400-X-2023',
    nImpot: 'A0142891Z',
    adresse: 'Avenue du Ciment 42',
    ville: 'Lubumbashi',
    pays: 'RDC',
    telephone: '+243 99 000 0000',
    email: 'contact@transafrique.cd',
    devise: 'USD',
    exerciceEnCours: '2025',
    dateDebut: '2025-01-01',
    dateFin: '2025-12-31',
  },
  {
    id: 'd2',
    raisonSociale: 'Sabri Mining Logistics SA',
    sigle: 'SML',
    statutJuridique: 'SA',
    rccm: 'RCC/CD/HKT/2021/A-0089',
    idNat: '01-N8-K7400-Y-2021',
    nImpot: 'A0089123B',
    adresse: 'Route de la Mine, Sabri',
    ville: 'Sabri',
    pays: 'RDC',
    telephone: '+243 81 111 1111',
    email: 'info@sabrimining.cd',
    devise: 'USD',
    exerciceEnCours: '2025',
    dateDebut: '2025-01-01',
    dateFin: '2025-12-31',
  },
  {
    id: 'd3',
    raisonSociale: 'Dangote Procurement Zambia Ltd',
    sigle: 'DPL',
    statutJuridique: 'Ltd',
    rccm: 'PACRA/ZM/2020/045678',
    idNat: 'ZM-2020-045678',
    nImpot: 'ZM-TPIN-045678',
    adresse: 'Levy Mwanawasa Stadium Rd',
    ville: 'Ndola',
    pays: 'Zambia',
    telephone: '+260 96 222 2222',
    email: 'procurement@dangote.zm',
    devise: 'USD',
    exerciceEnCours: '2025',
    dateDebut: '2025-01-01',
    dateFin: '2025-12-31',
  },
];

export const JOURNAUX: Journal[] = [
  { code: 'ACH', libelle: 'Journal des Achats', type: 'achats', site: 'zambie', dernierNumero: 142 },
  { code: 'VTE', libelle: 'Journal des Ventes', type: 'ventes', site: 'lubumbashi', dernierNumero: 98 },
  { code: 'CAI', libelle: 'Journal de Caisse', type: 'caisse', site: 'zambie', dernierNumero: 67 },
  { code: 'BQ', libelle: 'Journal de Banque', type: 'banque', site: 'lubumbashi', dernierNumero: 234 },
  { code: 'OD', libelle: 'Operations Diverses', type: 'od', site: 'lubumbashi', dernierNumero: 89 },
  { code: 'FISC', libelle: 'Journal Fiscal', type: 'od', site: 'lubumbashi', dernierNumero: 15 },
];

export const PLAN_COMPTABLE: CompteComptable[] = [
  { numero: '10', libelle: 'Capital', classe: '1', type: 'general', lettable: false, soldeDebit: 0, soldeCredit: 500000 },
  { numero: '101', libelle: 'Capital social', classe: '1', type: 'general', parent: '10', lettable: false, soldeDebit: 0, soldeCredit: 500000 },
  { numero: '12', libelle: 'Report a nouveau', classe: '1', type: 'general', lettable: false, soldeDebit: 0, soldeCredit: 45000 },
  { numero: '13', libelle: 'Resultats nets en instance', classe: '1', type: 'general', lettable: false, soldeDebit: 0, soldeCredit: 78000 },
  { numero: '16', libelle: 'Emprunts et dettes', classe: '1', type: 'general', lettable: false, soldeDebit: 0, soldeCredit: 120000 },
  { numero: '20', libelle: 'Immobilisations incorporelles', classe: '2', type: 'general', lettable: false, soldeDebit: 85000, soldeCredit: 0 },
  { numero: '21', libelle: 'Immobilisations corporelles', classe: '2', type: 'general', lettable: false, soldeDebit: 320000, soldeCredit: 0 },
  { numero: '210', libelle: 'Terrains', classe: '2', type: 'general', parent: '21', lettable: false, soldeDebit: 120000, soldeCredit: 0 },
  { numero: '211', libelle: 'Batiments', classe: '2', type: 'general', parent: '21', lettable: false, soldeDebit: 180000, soldeCredit: 0 },
  { numero: '212', libelle: 'Materiel et outillage', classe: '2', type: 'general', parent: '21', lettable: false, soldeDebit: 20000, soldeCredit: 0 },
  { numero: '245', libelle: 'Materiel de transport', classe: '2', type: 'general', parent: '24', lettable: false, soldeDebit: 45000, soldeCredit: 0 },
  { numero: '28', libelle: 'Amortissements', classe: '2', type: 'general', lettable: false, soldeDebit: 0, soldeCredit: 125000 },
  { numero: '30', libelle: 'Approvisionnements et marchandises', classe: '3', type: 'general', lettable: false, soldeDebit: 180000, soldeCredit: 0 },
  { numero: '31', libelle: 'Stocks de marchandises (Ciment)', classe: '3', type: 'general', parent: '30', lettable: false, soldeDebit: 180000, soldeCredit: 0 },
  { numero: '36', libelle: 'Stocks en transit', classe: '3', type: 'general', lettable: false, soldeDebit: 65000, soldeCredit: 0 },
  { numero: '40', libelle: 'Fournisseurs et comptes rattaches', classe: '4', type: 'general', lettable: false, soldeDebit: 0, soldeCredit: 245000 },
  { numero: '401', libelle: 'Fournisseurs', classe: '4', type: 'general', parent: '40', lettable: true, soldeDebit: 0, soldeCredit: 245000 },
  { numero: '401-DANGOTE', libelle: 'Dangote Cement Zambia', classe: '4', type: 'auxiliaire', parent: '401', lettable: true, soldeDebit: 0, soldeCredit: 180000, tiers: { code: 'DANGOTE', nom: 'Dangote Cement Zambia', type: 'fournisseur' } },
  { numero: '401-TRANS', libelle: 'TransAfrique Logistics', classe: '4', type: 'auxiliaire', parent: '401', lettable: true, soldeDebit: 0, soldeCredit: 45000, tiers: { code: 'TRANS', nom: 'TransAfrique Logistics', type: 'fournisseur' } },
  { numero: '401-RAWBANK', libelle: 'Rawbank - Frais bancaires', classe: '4', type: 'auxiliaire', parent: '401', lettable: true, soldeDebit: 0, soldeCredit: 20000, tiers: { code: 'RAWBANK', nom: 'Rawbank', type: 'fournisseur' } },
  { numero: '41', libelle: 'Clients et comptes rattaches', classe: '4', type: 'general', lettable: false, soldeDebit: 0, soldeCredit: 0 },
  { numero: '411', libelle: 'Clients', classe: '4', type: 'general', parent: '41', lettable: true, soldeDebit: 320000, soldeCredit: 0 },
  { numero: '411-SABRI', libelle: 'Mine de Sabri', classe: '4', type: 'auxiliaire', parent: '411', lettable: true, soldeDebit: 210000, soldeCredit: 0, tiers: { code: 'SABRI', nom: 'Mine de Sabri', type: 'client' } },
  { numero: '411-KCC', libelle: 'Kamoto Copper Company', classe: '4', type: 'auxiliaire', parent: '411', lettable: true, soldeDebit: 110000, soldeCredit: 0, tiers: { code: 'KCC', nom: 'Kamoto Copper Company', type: 'client' } },
  { numero: '42', libelle: 'Personnel', classe: '4', type: 'general', lettable: false, soldeDebit: 0, soldeCredit: 0 },
  { numero: '422', libelle: 'Remunerations dues au personnel', classe: '4', type: 'general', parent: '42', lettable: false, soldeDebit: 0, soldeCredit: 38000 },
  { numero: '43', libelle: 'Organismes sociaux', classe: '4', type: 'general', lettable: false, soldeDebit: 0, soldeCredit: 12000 },
  { numero: '44', libelle: 'Etat et collectivites publiques', classe: '4', type: 'general', lettable: false, soldeDebit: 0, soldeCredit: 0 },
  { numero: '441', libelle: 'Impots et taxes a payer', classe: '4', type: 'general', parent: '44', lettable: false, soldeDebit: 0, soldeCredit: 28000 },
  { numero: '442', libelle: 'TVA collectee', classe: '4', type: 'general', parent: '44', lettable: false, soldeDebit: 0, soldeCredit: 42000 },
  { numero: '445', libelle: 'TVA deductible', classe: '4', type: 'general', parent: '44', lettable: false, soldeDebit: 18000, soldeCredit: 0 },
  { numero: '50', libelle: 'Titres de placement', classe: '5', type: 'general', lettable: false, soldeDebit: 0, soldeCredit: 0 },
  { numero: '52', libelle: 'Banques', classe: '5', type: 'general', lettable: false, soldeDebit: 0, soldeCredit: 0 },
  { numero: '521', libelle: 'Banque Rawbank USD', classe: '5', type: 'general', parent: '52', lettable: false, soldeDebit: 285000, soldeCredit: 0 },
  { numero: '522', libelle: 'Banque Rawbank CDF', classe: '5', type: 'general', parent: '52', lettable: false, soldeDebit: 45000, soldeCredit: 0 },
  { numero: '53', libelle: 'Caisses', classe: '5', type: 'general', lettable: false, soldeDebit: 0, soldeCredit: 0 },
  { numero: '531', libelle: 'Caisse Zambie', classe: '5', type: 'general', parent: '53', lettable: false, soldeDebit: 18000, soldeCredit: 0 },
  { numero: '532', libelle: 'Caisse Lubumbashi', classe: '5', type: 'general', parent: '53', lettable: false, soldeDebit: 12000, soldeCredit: 0 },
  { numero: '533', libelle: 'Caisse Sabri', classe: '5', type: 'general', parent: '53', lettable: false, soldeDebit: 8500, soldeCredit: 0 },
  { numero: '60', libelle: 'Achats et variations de stocks', classe: '6', type: 'general', lettable: false, soldeDebit: 0, soldeCredit: 0 },
  { numero: '601', libelle: 'Achats de marchandises (Ciment)', classe: '6', type: 'general', parent: '60', lettable: false, soldeDebit: 520000, soldeCredit: 0 },
  { numero: '61', libelle: 'Transports', classe: '6', type: 'general', lettable: false, soldeDebit: 145000, soldeCredit: 0 },
  { numero: '611', libelle: 'Transport sur achats', classe: '6', type: 'general', parent: '61', lettable: false, soldeDebit: 85000, soldeCredit: 0 },
  { numero: '612', libelle: 'Transport sur ventes', classe: '6', type: 'general', parent: '61', lettable: false, soldeDebit: 60000, soldeCredit: 0 },
  { numero: '62', libelle: 'Services exterieurs', classe: '6', type: 'general', lettable: false, soldeDebit: 38000, soldeCredit: 0 },
  { numero: '63', libelle: 'Frais de personnel', classe: '6', type: 'general', lettable: false, soldeDebit: 62000, soldeCredit: 0 },
  { numero: '64', libelle: 'Impots et taxes', classe: '6', type: 'general', lettable: false, soldeDebit: 28000, soldeCredit: 0 },
  { numero: '65', libelle: 'Autres charges', classe: '6', type: 'general', lettable: false, soldeDebit: 15000, soldeCredit: 0 },
  { numero: '66', libelle: 'Charges financieres', classe: '6', type: 'general', lettable: false, soldeDebit: 8500, soldeCredit: 0 },
  { numero: '67', libelle: 'Pertes de change', classe: '6', type: 'general', lettable: false, soldeDebit: 3200, soldeCredit: 0 },
  { numero: '68', libelle: 'Dotations aux amortissements', classe: '6', type: 'general', lettable: false, soldeDebit: 25000, soldeCredit: 0 },
  { numero: '70', libelle: 'Ventes de marchandises', classe: '7', type: 'general', lettable: false, soldeDebit: 0, soldeCredit: 780000 },
  { numero: '701', libelle: 'Ventes de ciment', classe: '7', type: 'general', parent: '70', lettable: false, soldeDebit: 0, soldeCredit: 780000 },
  { numero: '75', libelle: 'Autres produits', classe: '7', type: 'general', lettable: false, soldeDebit: 0, soldeCredit: 12000 },
  { numero: '76', libelle: 'Produits financiers', classe: '7', type: 'general', lettable: false, soldeDebit: 0, soldeCredit: 4500 },
  { numero: '77', libelle: 'Gains de change', classe: '7', type: 'general', lettable: false, soldeDebit: 0, soldeCredit: 1800 },
  { numero: '80', libelle: 'Engagements', classe: '8', type: 'general', lettable: false, soldeDebit: 0, soldeCredit: 0 },
  { numero: '89', libelle: 'Bilan', classe: '8', type: 'general', lettable: false, soldeDebit: 0, soldeCredit: 0 },
];

export const CLASSES_SYSCOHADA = [
  { classe: '1', libelle: 'Comptes de capitaux', couleur: 'hsl(221 83% 53%)' },
  { classe: '2', libelle: "Comptes d'immobilisations", couleur: 'hsl(280 65% 60%)' },
  { classe: '3', libelle: 'Comptes de stocks', couleur: 'hsl(38 92% 50%)' },
  { classe: '4', libelle: 'Comptes de tiers', couleur: 'hsl(142 71% 45%)' },
  { classe: '5', libelle: 'Comptes de tresorerie', couleur: 'hsl(0 84% 60%)' },
  { classe: '6', libelle: 'Comptes de charges', couleur: 'hsl(24 95% 53%)' },
  { classe: '7', libelle: 'Comptes de produits', couleur: 'hsl(173 58% 39%)' },
  { classe: '8', libelle: 'Comptes des autres postes', couleur: 'hsl(280 65% 60%)' },
];

export const ECRITURES: Ecriture[] = [
  {
    id: 'e1',
    numero: 'ACH-2025-00142',
    journal: 'ACH',
    date: '2025-07-05',
    libelle: 'Facture Dangote Cement - 50 tonnes ciment',
    statut: 'valide',
    saisiePar: 'Mwamba Kalonji',
    validePar: 'Sarah Mukendi',
    piece: 'FAC-DANG-2025-0742.pdf',
    lignes: [
      { id: 'l1', date: '2025-07-05', compte: '601', libelleCompte: 'Achats de marchandises (Ciment)', libelle: '50 tonnes ciment Portland', debit: 48000, credit: 0, auxiliaire: '401-DANGOTE' },
      { id: 'l2', date: '2025-07-05', compte: '445', libelleCompte: 'TVA deductible', libelle: 'TVA deductible 16%', debit: 7680, credit: 0 },
      { id: 'l3', date: '2025-07-05', compte: '401-DANGOTE', libelleCompte: 'Dangote Cement Zambia', libelle: 'Facture FAC-DANG-2025-0742', debit: 0, credit: 55680, auxiliaire: '401-DANGOTE' },
    ],
  },
  {
    id: 'e2',
    numero: 'VTE-2025-00098',
    journal: 'VTE',
    date: '2025-07-06',
    libelle: 'Facture vente ciment - Mine de Sabri',
    statut: 'valide',
    saisiePar: 'Sarah Mukendi',
    validePar: 'Sarah Mukendi',
    piece: 'FAC-VTE-2025-0098.pdf',
    lignes: [
      { id: 'l1', date: '2025-07-06', compte: '411-SABRI', libelleCompte: 'Mine de Sabri', libelle: 'Vente 45 tonnes ciment', debit: 69600, credit: 0, auxiliaire: '411-SABRI' },
      { id: 'l2', date: '2025-07-06', compte: '701', libelleCompte: 'Ventes de ciment', libelle: 'Vente 45 tonnes', debit: 0, credit: 60000 },
      { id: 'l3', date: '2025-07-06', compte: '442', libelleCompte: 'TVA collectee', libelle: 'TVA 16%', debit: 0, credit: 9600 },
    ],
  },
  {
    id: 'e3',
    numero: 'BQ-2025-00234',
    journal: 'BQ',
    date: '2025-07-07',
    libelle: 'Paiement transporteur TransAfrique',
    statut: 'valide',
    saisiePar: 'Mwamba Kalonji',
    validePar: 'Sarah Mukendi',
    piece: 'ORD-VIR-2025-0234.pdf',
    lignes: [
      { id: 'l1', date: '2025-07-07', compte: '401-TRANS', libelleCompte: 'TransAfrique Logistics', libelle: 'Paiement facture TR-045', debit: 0, credit: 12500, auxiliaire: '401-TRANS' },
      { id: 'l2', date: '2025-07-07', compte: '521', libelleCompte: 'Banque Rawbank USD', libelle: 'Virement TransAfrique', debit: 12500, credit: 0 },
    ],
  },
  {
    id: 'e4',
    numero: 'CAI-2025-00067',
    journal: 'CAI',
    date: '2025-07-07',
    libelle: 'Sortie caisse Zambie - Achat carburant camion',
    statut: 'brouillard',
    saisiePar: 'Joseph Kabongo',
    piece: 'RECU-CARB-0742.jpg',
    lignes: [
      { id: 'l1', date: '2025-07-07', compte: '611', libelleCompte: 'Transport sur achats', libelle: 'Carburant camion AS-4521', debit: 850, credit: 0 },
      { id: 'l2', date: '2025-07-07', compte: '531', libelleCompte: 'Caisse Zambie', libelle: 'Sortie caisse', debit: 0, credit: 850 },
    ],
  },
  {
    id: 'e5',
    numero: 'OD-2025-00089',
    journal: 'OD',
    date: '2025-07-08',
    libelle: 'Dotation amortissement mensuelle',
    statut: 'brouillard',
    saisiePar: 'Sarah Mukendi',
    lignes: [
      { id: 'l1', date: '2025-07-08', compte: '68', libelleCompte: 'Dotations aux amortissements', libelle: 'Dotation juillet 2025', debit: 2083, credit: 0 },
      { id: 'l2', date: '2025-07-08', compte: '28', libelleCompte: 'Amortissements', libelle: 'Contrepartie dotation', debit: 0, credit: 2083 },
    ],
  },
];

export const TIERS: Tiers[] = [
  {
    code: 'DANGOTE',
    nom: 'Dangote Cement Zambia',
    type: 'fournisseur',
    compte: '401-DANGOTE',
    soldeDebit: 0,
    soldeCredit: 180000,
    balanceAgee: [
      { periode: '0-30j', montant: 85000 },
      { periode: '31-60j', montant: 60000 },
      { periode: '61-90j', montant: 35000 },
      { periode: '+90j', montant: 0 },
    ],
  },
  {
    code: 'TRANS',
    nom: 'TransAfrique Logistics',
    type: 'fournisseur',
    compte: '401-TRANS',
    soldeDebit: 0,
    soldeCredit: 45000,
    balanceAgee: [
      { periode: '0-30j', montant: 12500 },
      { periode: '31-60j', montant: 18000 },
      { periode: '61-90j', montant: 14500 },
      { periode: '+90j', montant: 0 },
    ],
  },
  {
    code: 'SABRI',
    nom: 'Mine de Sabri',
    type: 'client',
    compte: '411-SABRI',
    soldeDebit: 210000,
    soldeCredit: 0,
    balanceAgee: [
      { periode: '0-30j', montant: 69600 },
      { periode: '31-60j', montant: 85000 },
      { periode: '61-90j', montant: 55400 },
      { periode: '+90j', montant: 0 },
    ],
  },
  {
    code: 'KCC',
    nom: 'Kamoto Copper Company',
    type: 'client',
    compte: '411-KCC',
    soldeDebit: 110000,
    soldeCredit: 0,
    balanceAgee: [
      { periode: '0-30j', montant: 45000 },
      { periode: '31-60j', montant: 38000 },
      { periode: '61-90j', montant: 27000 },
      { periode: '+90j', montant: 0 },
    ],
  },
];

export const CAMIONS: Camion[] = [
  {
    id: 'c1',
    immat: 'AS-4521-ZM',
    chauffeur: 'Patrick Mwamba',
    transporteur: 'TransAfrique Logistics',
    chargement: 34,
    statut: 'transit_zambie',
    dateDepart: '2025-07-06T06:00:00',
    position: 'Kapiri Mposhi, Zambie',
    progression: 35,
    bl: 'BL-2025-0142',
    factureTransport: 4200,
    douaneMontant: 0,
  },
  {
    id: 'c2',
    immat: 'AS-8832-ZM',
    chauffeur: 'Jean-Luc Kabongo',
    transporteur: 'TransAfrique Logistics',
    chargement: 34,
    statut: 'douane_rdc',
    dateDepart: '2025-07-05T05:30:00',
    position: 'Poste frontiere Kasumbalesa, RDC',
    progression: 65,
    bl: 'BL-2025-0141',
    factureTransport: 4200,
    douaneMontant: 6800,
  },
  {
    id: 'c3',
    immat: 'AS-2204-ZM',
    chauffeur: 'Moise Tshibangu',
    transporteur: 'TransAfrique Logistics',
    chargement: 34,
    statut: 'arrive_sabri',
    dateDepart: '2025-07-04T04:00:00',
    dateArrivee: '2025-07-07T18:30:00',
    position: 'Mine de Sabri, RDC',
    progression: 100,
    bl: 'BL-2025-0140',
    factureTransport: 4200,
    douaneMontant: 6800,
  },
  {
    id: 'c4',
    immat: 'AS-9981-ZM',
    chauffeur: 'Emmanuel Ilunga',
    transporteur: 'TransAfrique Logistics',
    chargement: 34,
    statut: 'chargement',
    dateDepart: '2025-07-08T07:00:00',
    position: 'Depot Dangote, Ndola, Zambie',
    progression: 5,
    bl: 'BL-2025-0143',
    factureTransport: 4200,
    douaneMontant: 0,
  },
  {
    id: 'c5',
    immat: 'AS-3345-ZM',
    chauffeur: 'Olivier Nkulu',
    transporteur: 'TransAfrique Logistics',
    chargement: 34,
    statut: 'douane_zambie',
    dateDepart: '2025-07-05T08:00:00',
    position: 'Poste frontiere Kasumbalesa, Zambie',
    progression: 50,
    bl: 'BL-2025-0139',
    factureTransport: 4200,
    douaneMontant: 0,
  },
  {
    id: 'c6',
    immat: 'AS-7723-ZM',
    chauffeur: 'Christian Bwalya',
    transporteur: 'TransAfrique Logistics',
    chargement: 34,
    statut: 'transit_rdc',
    dateDepart: '2025-07-06T03:00:00',
    position: 'Route Lubumbashi-Sabri, km 45',
    progression: 85,
    bl: 'BL-2025-0144',
    factureTransport: 4200,
    douaneMontant: 6800,
  },
];

export const FACTURES: Facture[] = [
  { id: 'f1', numero: 'FAC-VTE-2025-0098', date: '2025-07-06', client: 'Mine de Sabri', montantHT: 60000, tva: 9600, montantTTC: 69600, statut: 'impayee', echeance: '2025-08-05' },
  { id: 'f2', numero: 'FAC-VTE-2025-0097', date: '2025-07-04', client: 'Kamoto Copper Company', montantHT: 45000, tva: 7200, montantTTC: 52200, statut: 'partielle', echeance: '2025-08-03' },
  { id: 'f3', numero: 'FAC-VTE-2025-0096', date: '2025-07-02', client: 'Mine de Sabri', montantHT: 55000, tva: 8800, montantTTC: 63800, statut: 'payee', echeance: '2025-08-01' },
  { id: 'f4', numero: 'FAC-VTE-2025-0095', date: '2025-06-30', client: 'Kamoto Copper Company', montantHT: 38000, tva: 6080, montantTTC: 44080, statut: 'payee', echeance: '2025-07-30' },
  { id: 'f5', numero: 'FAC-VTE-2025-0094', date: '2025-06-28', client: 'Mine de Sabri', montantHT: 42000, tva: 6720, montantTTC: 48720, statut: 'impayee', echeance: '2025-07-28' },
  { id: 'f6', numero: 'FAC-VTE-2025-0093', date: '2025-06-25', client: 'Kamoto Copper Company', montantHT: 52000, tva: 8320, montantTTC: 60320, statut: 'payee', echeance: '2025-07-25' },
];

export const IMMOBILISATIONS: Immobilisation[] = [
  { id: 'i1', code: 'IM-001', libelle: 'Camion Mercedes Actros 2545', categorie: 'Materiel de transport', dateAcquisition: '2023-03-15', valeurAcquisition: 85000, duree: 5, methode: 'lineaire', cumulAmortissement: 42500, vnc: 42500, dotationAnnuelle: 17000, site: 'zambie' },
  { id: 'i2', code: 'IM-002', libelle: 'Batiment Bureau Lubumbashi', categorie: 'Batiments', dateAcquisition: '2021-01-10', valeurAcquisition: 180000, duree: 20, methode: 'lineaire', cumulAmortissement: 40500, vnc: 139500, dotationAnnuelle: 9000, site: 'lubumbashi' },
  { id: 'i3', code: 'IM-003', libelle: 'Logiciel de comptabilite', categorie: 'Logiciels', dateAcquisition: '2022-06-01', valeurAcquisition: 25000, duree: 3, methode: 'lineaire', cumulAmortissement: 25000, vnc: 0, dotationAnnuelle: 8333, site: 'lubumbashi' },
  { id: 'i4', code: 'IM-004', libelle: 'Mobilier de bureau', categorie: 'Mobilier', dateAcquisition: '2023-09-20', valeurAcquisition: 15000, duree: 10, methode: 'lineaire', cumulAmortissement: 2625, vnc: 12375, dotationAnnuelle: 1500, site: 'lubumbashi' },
  { id: 'i5', code: 'IM-005', libelle: 'Groupe electrogene Sabri', categorie: 'Installations techniques', dateAcquisition: '2024-02-14', valeurAcquisition: 32000, duree: 8, methode: 'lineaire', cumulAmortissement: 6000, vnc: 26000, dotationAnnuelle: 4000, site: 'sabri' },
  { id: 'i6', code: 'IM-006', libelle: 'Camion Volvo FH16', categorie: 'Materiel de transport', dateAcquisition: '2024-05-10', valeurAcquisition: 95000, duree: 5, methode: 'lineaire', cumulAmortissement: 19000, vnc: 76000, dotationAnnuelle: 19000, site: 'zambie' },
];

export const AUDIT_ENTRIES: AuditEntry[] = [
  { id: 'a1', timestamp: '2025-07-08T14:32:15', utilisateur: 'Sarah Mukendi', role: 'Comptable Senior', ip: '192.168.1.42', terminal: 'Desktop - Chrome', action: 'VALIDATION', module: 'Comptabilite', objet: 'Ecriture #ACH-2025-00142 dans Journal Achats' },
  { id: 'a2', timestamp: '2025-07-08T14:28:03', utilisateur: 'Mwamba Kalonji', role: 'Comptable', ip: '192.168.1.38', terminal: 'Desktop - Firefox', action: 'CREATION', module: 'Comptabilite', objet: 'Ecriture #BQ-2025-00234 dans Journal Banque' },
  { id: 'a3', timestamp: '2025-07-08T14:15:42', utilisateur: 'Joseph Kabongo', role: 'Operateur Terrain', ip: '10.0.5.12', terminal: 'Mobile - Safari iOS', action: 'CREATION', module: 'Saisie Terrain', objet: 'Ecriture #CAI-2025-00067 dans Caisse Zambie' },
  { id: 'a4', timestamp: '2025-07-08T13:58:21', utilisateur: 'Sarah Mukendi', role: 'Comptable Senior', ip: '192.168.1.42', terminal: 'Desktop - Chrome', action: 'MODIFICATION', module: 'Plan Comptable', objet: 'Compte auxiliaire 401-DANGOTE', avant: 'Libelle: "Dangote"', apres: 'Libelle: "Dangote Cement Zambia"' },
  { id: 'a5', timestamp: '2025-07-08T13:42:10', utilisateur: 'Sarah Mukendi', role: 'Comptable Senior', ip: '192.168.1.42', terminal: 'Desktop - Chrome', action: 'CONNEXION', module: 'Authentification', objet: 'Connexion reussie' },
  { id: 'a6', timestamp: '2025-07-08T12:30:55', utilisateur: 'Joseph Kabongo', role: 'Operateur Terrain', ip: '10.0.5.12', terminal: 'Mobile - Safari iOS', action: 'CONNEXION', module: 'Authentification', objet: 'Connexion reussie (mode offline)' },
  { id: 'a7', timestamp: '2025-07-08T11:45:33', utilisateur: 'Mwamba Kalonji', role: 'Comptable', ip: '192.168.1.38', terminal: 'Desktop - Firefox', action: 'LECTURE', module: 'Restitutions', objet: 'Consultation Grand Livre compte 401' },
  { id: 'a8', timestamp: '2025-07-08T10:22:18', utilisateur: 'Sarah Mukendi', role: 'Comptable Senior', ip: '192.168.1.42', terminal: 'Desktop - Chrome', action: 'EXPORTATION', module: 'Restitutions', objet: 'Export PDF Balance Generale' },
  { id: 'a9', timestamp: '2025-07-08T09:15:02', utilisateur: 'Sarah Mukendi', role: 'Comptable Senior', ip: '192.168.1.42', terminal: 'Desktop - Chrome', action: 'VALIDATION', module: 'Logistique', objet: 'Validation passage camion AS-8832-ZM' },
  { id: 'a10', timestamp: '2025-07-08T08:48:44', utilisateur: 'Mwamba Kalonji', role: 'Comptable', ip: '192.168.1.38', terminal: 'Desktop - Firefox', action: 'CREATION', module: 'Ventes', objet: 'Facture FAC-VTE-2025-0098' },
  { id: 'a11', timestamp: '2025-07-07T17:32:15', utilisateur: 'Sarah Mukendi', role: 'Comptable Senior', ip: '192.168.1.42', terminal: 'Desktop - Chrome', action: 'SUPPRESSION', module: 'Comptabilite', objet: 'Ecriture brouillard #OD-2025-00088 (annulee)' },
  { id: 'a12', timestamp: '2025-07-07T16:20:30', utilisateur: 'Joseph Kabongo', role: 'Operateur Terrain', ip: '10.0.5.12', terminal: 'Mobile - Safari iOS', action: 'CREATION', module: 'Saisie Terrain', objet: 'Photo recue carburant RECU-CARB-0742.jpg' },
];

export const KPIS_DASHBOARD: KPI[] = [
  { label: 'Tresorerie globale', value: 368500, format: 'currency', evolution: 12.5, icon: 'wallet', color: 'hsl(142 71% 45%)' },
  { label: "Chiffre d'affaires (YTD)", value: 780000, format: 'currency', evolution: 18.3, icon: 'trending-up', color: 'hsl(221 83% 53%)' },
  { label: 'Creances clients', value: 320000, format: 'currency', evolution: -5.2, icon: 'users', color: 'hsl(38 92% 50%)' },
  { label: 'Dettes fournisseurs', value: 245000, format: 'currency', evolution: 8.1, icon: 'truck', color: 'hsl(280 65% 60%)' },
];

export const RELEVE_BANCAIRE: LigneReleve[] = [
  { id: 'r1', date: '2025-07-01', libelle: 'Virement recu - Mine de Sabri', montant: 69600, sens: 'credit', pointe: false },
  { id: 'r2', date: '2025-07-03', libelle: 'Virement emis - TransAfrique Logistics', montant: 12500, sens: 'debit', pointe: false },
  { id: 'r3', date: '2025-07-05', libelle: 'Frais bancaire Rawbank', montant: 45, sens: 'debit', pointe: false },
  { id: 'r4', date: '2025-07-06', libelle: 'Virement recu - Kamoto Copper Co', montant: 45000, sens: 'credit', pointe: false },
  { id: 'r5', date: '2025-07-07', libelle: 'Prelevement ARSP', montant: 1200, sens: 'debit', pointe: false },
  { id: 'r6', date: '2025-07-08', libelle: 'Agios decouvert Q2', montant: 180, sens: 'debit', pointe: false },
];

export const COMPTA_BANQUE: LigneCompta[] = [
  { id: 'c1', date: '2025-07-01', libelle: 'Encaissement client Sabri', compte: '521', montant: 69600, sens: 'debit', pointe: false },
  { id: 'c2', date: '2025-07-03', libelle: 'Paiement transporteur', compte: '521', montant: 12500, sens: 'credit', pointe: false },
  { id: 'c3', date: '2025-07-06', libelle: 'Encaissement KCC', compte: '521', montant: 45000, sens: 'debit', pointe: false },
  { id: 'c4', date: '2025-07-07', libelle: 'Prelevement ARSP', compte: '521', montant: 1200, sens: 'credit', pointe: false },
];

export const CHART_CASHFLOW = [
  { mois: 'Jan', entrees: 65000, sorties: 42000, solde: 23000 },
  { mois: 'Fev', entrees: 72000, sorties: 48000, solde: 47000 },
  { mois: 'Mar', entrees: 81000, sorties: 55000, solde: 73000 },
  { mois: 'Avr', entrees: 68000, sorties: 51000, solde: 90000 },
  { mois: 'Mai', entrees: 95000, sorties: 62000, solde: 123000 },
  { mois: 'Juin', entrees: 88000, sorties: 58000, solde: 153000 },
  { mois: 'Juil', entrees: 114600, sorties: 63725, solde: 204375 },
];

export const CHART_RENTABILITE = [
  { voyage: 'V-142', ca: 69600, couts: 52000, marge: 17600 },
  { voyage: 'V-141', ca: 69600, couts: 48500, marge: 21100 },
  { voyage: 'V-140', ca: 69600, couts: 55000, marge: 14600 },
  { voyage: 'V-139', ca: 69600, couts: 47000, marge: 22600 },
  { voyage: 'V-138', ca: 69600, couts: 51000, marge: 18600 },
  { voyage: 'V-137', ca: 69600, couts: 49000, marge: 20600 },
];

export const CHART_EXPLOSION_CHARGES = [
  { name: 'Achats ciment', value: 520000, color: 'hsl(221 83% 53%)' },
  { name: 'Transport', value: 145000, color: 'hsl(38 92% 50%)' },
  { name: 'Frais personnel', value: 62000, color: 'hsl(142 71% 45%)' },
  { name: 'Services exterieurs', value: 38000, color: 'hsl(280 65% 60%)' },
  { name: 'Impots et taxes', value: 28000, color: 'hsl(0 84% 60%)' },
  { name: 'Autres charges', value: 15000, color: 'hsl(24 95% 53%)' },
];

export const ACTIVITES_RECENTES = [
  { id: 'ac1', user: 'Sarah Mukendi', action: "a valide l'ecriture", objet: 'ACH-2025-00142', time: 'Il y a 12 min', type: 'validation' },
  { id: 'ac2', user: 'Joseph Kabongo', action: 'a saisi une sortie de caisse', objet: 'CAI-2025-00067', time: 'Il y a 28 min', type: 'creation' },
  { id: 'ac3', user: 'Mwamba Kalonji', action: 'a cree la facture', objet: 'FAC-VTE-2025-0098', time: 'Il y a 1h', type: 'creation' },
  { id: 'ac4', user: 'Sarah Mukendi', action: 'a exporte la Balance Generale', objet: 'PDF', time: 'Il y a 2h', type: 'export' },
  { id: 'ac5', user: 'Systeme', action: 'a detecte une anomalie sur', objet: 'compte 611 (variation +34%)', time: 'Il y a 3h', type: 'alerte' },
  { id: 'ac6', user: 'Mwamba Kalonji', action: 'a consulte le Grand Livre', objet: 'compte 401', time: 'Il y a 4h', type: 'lecture' },
];

export const NOTIFICATIONS = [
  { id: 'n1', titre: 'Anomalie detectee', message: 'Variation anormale sur le compte 611 (+34%)', time: 'Il y a 3h', type: 'warning' as const, lu: false },
  { id: 'n2', titre: 'Camion en attente de dedouanement', message: 'AS-8832-ZM bloque a Kasumbalesa RDC', time: 'Il y a 1h', type: 'info' as const, lu: false },
  { id: 'n3', titre: 'Facture impayee', message: 'FAC-VTE-2025-0094 echeance dans 20 jours', time: 'Il y a 5h', type: 'error' as const, lu: false },
  { id: 'n4', titre: 'Cloture mensuelle', message: 'Periode de juin prete pour cloture', time: 'Hier', type: 'success' as const, lu: true },
];

export const UTILISATEUR_COURANT = {
  nom: 'Sarah Mukendi',
  role: 'Comptable Senior',
  site: 'lubumbashi',
  avatar: 'https://images.pexels.com/photos/5905902/pexels-photo-5905902.jpeg?auto=compress&cs=tinysrgb&w=150',
  email: 's.mukendi@transafrique.cd',
};

export const PARAMETRES: Parametre[] = [
  { id: 'p1', cle: 'theme_apparence', valeur: 'system', categorie: 'apparence', typeValeur: 'string', description: 'Thème général de l\'application (light, dark, system)' },
  { id: 'p2', cle: 'devise_systeme', valeur: 'USD', categorie: 'finance', typeValeur: 'string', description: 'Devise par défaut pour l\'affichage des montants' },
  { id: 'p3', cle: 'langue_interface', valeur: 'fr-FR', categorie: 'localisation', typeValeur: 'string', description: 'Langue de l\'interface utilisateur' },
  { id: 'p4', cle: 'notifications_email', valeur: 'true', categorie: 'notifications', typeValeur: 'boolean', description: 'Activer l\'envoi de notifications par email' },
  { id: 'p5', cle: 'format_date', valeur: 'DD/MM/YYYY', categorie: 'localisation', typeValeur: 'string', description: 'Format d\'affichage des dates' },
  { id: 'p6', cle: 'notifications_push', valeur: 'true', categorie: 'notifications', typeValeur: 'boolean', description: 'Activer les notifications push dans le navigateur' },
  { id: 'p7', cle: 'notifications_alertes_stock', valeur: 'true', categorie: 'notifications', typeValeur: 'boolean', description: 'Notifier en cas de stock bas ou variation anormale' },
  { id: 'p8', cle: 'ia_assistance_comptable', valeur: 'true', categorie: 'ia', typeValeur: 'boolean', description: 'Activer l\'assistant IA pour l\'aide à la saisie comptable' },
  { id: 'p9', cle: 'ia_analyse_fiscale', valeur: 'false', categorie: 'ia', typeValeur: 'boolean', description: 'Utiliser l\'IA pour analyser les risques fiscaux' },
  { id: 'p10', cle: 'securite_2fa', valeur: 'true', categorie: 'securite', typeValeur: 'boolean', description: 'Forcer l\'authentification à deux facteurs (2FA)' },
  { id: 'p11', cle: 'securite_delai_session', valeur: '30', categorie: 'securite', typeValeur: 'number', description: 'Délai d\'inactivité avant déconnexion automatique (en minutes)' },
];
