# Generated by Django 6.0.7 on 2026-07-10 08:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immobilisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('libelle', models.CharField(max_length=255)),
                ('categorie', models.CharField(max_length=100)),
                ('dateAcquisition', models.DateField()),
                ('valeurAcquisition', models.DecimalField(decimal_places=2, max_digits=15)),
                ('duree', models.IntegerField(help_text='Durée en années')),
                ('methode', models.CharField(choices=[('lineaire', 'Linéaire'), ('degressive', 'Dégressive')], default='lineaire', max_length=20)),
                ('cumulAmortissement', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vnc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dotationAnnuelle', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('succursale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immobilisations', to='parametres.succursale')),
            ],
        ),
    ]
