# Generated by Django 6.0.7 on 2026-07-10 08:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('immat', models.CharField(max_length=50)),
                ('chauffeur', models.CharField(max_length=255)),
                ('transporteur', models.CharField(max_length=255)),
                ('chargement', models.DecimalField(decimal_places=2, help_text='Poids en tonnes', max_digits=10)),
                ('statut', models.CharField(choices=[('chargement', 'En Chargement'), ('transit_zambie', 'En Transit (Zambie)'), ('douane', 'Bloqué en Douane'), ('transit_rdc', 'En Transit (RDC)'), ('arrive_sabri', 'Arrivé à Sabri'), ('livre', 'Livré')], default='chargement', max_length=30)),
                ('dateDepart', models.DateTimeField(blank=True, null=True)),
                ('dateArrivee', models.DateTimeField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('progression', models.IntegerField(default=0)),
                ('bl', models.CharField(blank=True, max_length=100, null=True)),
                ('factureTransport', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('douaneMontant', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
    ]
